
import type { Bus, Trip, Seat, SeatStatus } from './types';

const createSeats = (price: number): (Seat | null)[][] => {
  const layout = [
    ['1', '2', null, '3', '4'],
    ['5', '6', null, '7', '8'],
    ['9', '10', null, '11', '12'],
    ['13', '14', null, '15', '16'],
    ['17', '18', null, '19', '20'],
    ['21', '22', null, '23', '24'],
    ['25', '26', null, '27', '28'],
    ['29', '30', null, '31', '32'],
    ['33', '34', null, '35', '36'],
    ['37', '38', '39', '40', '41'],
  ];

  let seatCounter = 1;
  return layout.map((row) =>
    row.map((seat) => {
      if (seat === null) {
        return null;
      }
      
      const randomStatus = Math.random();
      let status: SeatStatus = 'available';
      if (randomStatus < 0.3) status = 'booked';
      else if (randomStatus < 0.4 && seatCounter <= 8) status = 'ladies';

      const seatNumber = seatCounter.toString();
      seatCounter++;
      
      return {
        id: `${seatNumber}-${Math.random()}`,
        number: seatNumber,
        status: status,
        price,
      };
    })
  );
};

export const buses: Bus[] = [
  // Mumbai to Pune
  {
    id: '1',
    name: 'Blue Arrow Express',
    operator: 'Yatra Travels',
    departureTime: '21:00',
    arrivalTime: '05:00',
    duration: '8h 0m',
    from: 'Mumbai',
    to: 'Pune',
    price: 750,
    rating: 4.5,
    seats: createSeats(750),
  },
  {
    id: '2',
    name: 'Orange Dart',
    operator: 'Safar Tours',
    departureTime: '22:30',
    arrivalTime: '06:30',
    duration: '8h 0m',
    from: 'Mumbai',
    to: 'Pune',
    price: 800,
    rating: 4.2,
    seats: createSeats(800),
  },
  {
    id: '3',
    name: 'Comfort Cruiser',
    operator: 'Yatra Travels',
    departureTime: '20:00',
    arrivalTime: '04:30',
    duration: '8h 30m',
    from: 'Mumbai',
    to: 'Pune',
    price: 700,
    rating: 4.8,
    seats: createSeats(700),
  },

  // Pune to Mumbai
    {
    id: '19',
    name: 'Deccan Queen',
    operator: 'Safar Tours',
    departureTime: '19:00',
    arrivalTime: '03:00',
    duration: '8h 0m',
    from: 'Pune',
    to: 'Mumbai',
    price: 760,
    rating: 4.6,
    seats: createSeats(760),
  },
   {
    id: '20',
    name: 'Sinhagad Express',
    operator: 'Yatra Travels',
    departureTime: '23:00',
    arrivalTime: '07:00',
    duration: '8h 0m',
    from: 'Pune',
    to: 'Mumbai',
    price: 810,
    rating: 4.3,
    seats: createSeats(810),
  },
    {
    id: '21',
    name: 'Pragati Sleeper',
    operator: 'Patel Tours',
    departureTime: '21:00',
    arrivalTime: '05:30',
    duration: '8h 30m',
    from: 'Pune',
    to: 'Mumbai',
    price: 720,
    rating: 4.7,
    seats: createSeats(720),
  },


  // Ahmedabad to Mumbai
  {
    id: '4',
    name: 'Gujarat Queen',
    operator: 'Shree Travels',
    departureTime: '22:00',
    arrivalTime: '08:00',
    duration: '10h 0m',
    from: 'Ahmedabad',
    to: 'Mumbai',
    price: 950,
    rating: 4.4,
    seats: createSeats(950),
  },
  {
    id: '5',
    name: 'Sabarmati Link',
    operator: 'Patel Tours',
    departureTime: '21:30',
    arrivalTime: '07:00',
    duration: '9h 30m',
    from: 'Ahmedabad',
    to: 'Mumbai',
    price: 1000,
    rating: 4.6,
    seats: createSeats(1000),
  },
    {
    id: '6',
    name: 'Western Express',
    operator: 'Safar Tours',
    departureTime: '23:00',
    arrivalTime: '09:00',
    duration: '10h 0m',
    from: 'Ahmedabad',
    to: 'Mumbai',
    price: 900,
    rating: 4.1,
    seats: createSeats(900),
  },

  // Mumbai to Ahmedabad
  {
    id: '22',
    name: 'Mumbai-Ahm Superfast',
    operator: 'Shree Travels',
    departureTime: '21:00',
    arrivalTime: '07:00',
    duration: '10h 0m',
    from: 'Mumbai',
    to: 'Ahmedabad',
    price: 960,
    rating: 4.5,
    seats: createSeats(960),
  },
  {
    id: '23',
    name: 'Bandra-Sabarmati Spl',
    operator: 'Patel Tours',
    departureTime: '20:30',
    arrivalTime: '06:00',
    duration: '9h 30m',
    from: 'Mumbai',
    to: 'Ahmedabad',
    price: 1050,
    rating: 4.7,
    seats: createSeats(1050),
  },
  {
    id: '24',
    name: 'Dadar Western Link',
    operator: 'Safar Tours',
    departureTime: '22:00',
    arrivalTime: '08:00',
    duration: '10h 0m',
    from: 'Mumbai',
    to: 'Ahmedabad',
    price: 920,
    rating: 4.2,
    seats: createSeats(920),
  },

  // Mumbai to Delhi
  {
    id: '7',
    name: 'Capital Connect',
    operator: 'National Travels',
    departureTime: '18:00',
    arrivalTime: '16:00',
    duration: '22h 0m',
    from: 'Mumbai',
    to: 'Delhi',
    price: 2500,
    rating: 4.3,
    seats: createSeats(2500),
  },
  {
    id: '8',
    name: 'Rajdhani Bus Service',
    operator: 'Safar Tours',
    departureTime: '19:00',
    arrivalTime: '18:00',
    duration: '23h 0m',
    from: 'Mumbai',
    to: 'Delhi',
    price: 2800,
    rating: 4.7,
    seats: createSeats(2800),
  },
   {
    id: '9',
    name: 'Sovereign Sleeper',
    operator: 'Yatra Travels',
    departureTime: '20:00',
    arrivalTime: '19:00',
    duration: '23h 0m',
    from: 'Mumbai',
    to: 'Delhi',
    price: 2650,
    rating: 4.5,
    seats: createSeats(2650),
  },

  // Delhi to Mumbai
  {
    id: '25',
    name: 'Delhi-Mumbai Express',
    operator: 'National Travels',
    departureTime: '17:00',
    arrivalTime: '15:00',
    duration: '22h 0m',
    from: 'Delhi',
    to: 'Mumbai',
    price: 2550,
    rating: 4.4,
    seats: createSeats(2550),
  },
  {
    id: '26',
    name: 'Capital-Finance Link',
    operator: 'Safar Tours',
    departureTime: '18:00',
    arrivalTime: '17:00',
    duration: '23h 0m',
    from: 'Delhi',
    to: 'Mumbai',
    price: 2850,
    rating: 4.8,
    seats: createSeats(2850),
  },
  {
    id: '27',
    name: 'Yamuna Sleeper',
    operator: 'Yatra Travels',
    departureTime: '19:00',
    arrivalTime: '18:00',
    duration: '23h 0m',
    from: 'Delhi',
    to: 'Mumbai',
    price: 2700,
    rating: 4.6,
    seats: createSeats(2700),
  },


  // Delhi to Bangalore
  {
    id: '10',
    name: 'Deccan Odyssey',
    operator: 'Bharat Connect',
    departureTime: '15:00',
    arrivalTime: '03:00',
    duration: '36h 0m',
    from: 'Delhi',
    to: 'Bangalore',
    price: 4500,
    rating: 4.0,
    seats: createSeats(4500),
  },
  {
    id: '11',
    name: 'IT City Express',
    operator: 'Safar Tours',
    departureTime: '16:30',
    arrivalTime: '05:30',
    duration: '37h 0m',
    from: 'Delhi',
    to: 'Bangalore',
    price: 4800,
    rating: 4.2,
    seats: createSeats(4800),
  },
   {
    id: '12',
    name: 'Southern Star',
    operator: 'National Travels',
    departureTime: '14:00',
    arrivalTime: '02:00',
    duration: '36h 0m',
    from: 'Delhi',
    to: 'Bangalore',
    price: 4300,
    rating: 4.1,
    seats: createSeats(4300),
  },

  // Bangalore to Delhi
  {
    id: '28',
    name: 'Bangalore-Delhi Flyer',
    operator: 'Bharat Connect',
    departureTime: '14:00',
    arrivalTime: '02:00',
    duration: '36h 0m',
    from: 'Bangalore',
    to: 'Delhi',
    price: 4550,
    rating: 4.1,
    seats: createSeats(4550),
  },
  {
    id: '29',
    name: 'Silicon to Capital',
    operator: 'Safar Tours',
    departureTime: '15:30',
    arrivalTime: '04:30',
    duration: '37h 0m',
    from: 'Bangalore',
    to: 'Delhi',
    price: 4850,
    rating: 4.3,
    seats: createSeats(4850),
  },
  {
    id: '30',
    name: 'North Star',
    operator: 'National Travels',
    departureTime: '13:00',
    arrivalTime: '01:00',
    duration: '36h 0m',
    from: 'Bangalore',
    to: 'Delhi',
    price: 4350,
    rating: 4.0,
    seats: createSeats(4350),
  },

  
  // Bangalore to Chennai
  {
    id: '13',
    name: 'Garden City Flyer',
    operator: 'Yatra Travels',
    departureTime: '22:00',
    arrivalTime: '05:00',
    duration: '7h 0m',
    from: 'Bangalore',
    to: 'Chennai',
    price: 850,
    rating: 4.6,
    seats: createSeats(850),
  },
  {
    id: '14',
    name: 'Coromandel Express',
    operator: 'KPN Travels',
    departureTime: '23:00',
    arrivalTime: '06:30',
    duration: '7h 30m',
    from: 'Bangalore',
    to: 'Chennai',
    price: 900,
    rating: 4.5,
    seats: createSeats(900),
  },
   {
    id: '15',
    name: 'Marina Link',
    operator: 'Safar Tours',
    departureTime: '21:30',
    arrivalTime: '04:30',
    duration: '7h 0m',
    from: 'Bangalore',
    to: 'Chennai',
    price: 800,
    rating: 4.3,
    seats: createSeats(800),
  },
  
  // Chennai to Bangalore
  {
    id: '31',
    name: 'Chennai-Blr Express',
    operator: 'Yatra Travels',
    departureTime: '21:00',
    arrivalTime: '04:00',
    duration: '7h 0m',
    from: 'Chennai',
    to: 'Bangalore',
    price: 860,
    rating: 4.7,
    seats: createSeats(860),
  },
  {
    id: '32',
    name: 'East-West Link',
    operator: 'KPN Travels',
    departureTime: '22:00',
    arrivalTime: '05:30',
    duration: '7h 30m',
    from: 'Chennai',
    to: 'Bangalore',
    price: 910,
    rating: 4.6,
    seats: createSeats(910),
  },
  {
    id: '33',
    name: 'IT Corridor',
    operator: 'Safar Tours',
    departureTime: '20:30',
    arrivalTime: '03:30',
    duration: '7h 0m',
    from: 'Chennai',
    to: 'Bangalore',
    price: 820,
    rating: 4.4,
    seats: createSeats(820),
  },


  // Kolkata to Delhi
   {
    id: '16',
    name: 'Howrah-Delhi Janta',
    operator: 'Bengal Tours',
    departureTime: '17:00',
    arrivalTime: '20:00',
    duration: '27h 0m',
    from: 'Kolkata',
    to: 'Delhi',
    price: 3000,
    rating: 3.9,
    seats: createSeats(3000),
  },
  {
    id: '17',
    name: 'Grand Trunk Bus',
    operator: 'National Travels',
    departureTime: '18:30',
    arrivalTime: '22:00',
    duration: '27h 30m',
    from: 'Kolkata',
    to: 'Delhi',
    price: 3200,
    rating: 4.1,
    seats: createSeats(3200),
  },
  {
    id: '18',
    name: 'City of Joy Express',
    operator: 'Yatra Travels',
    departureTime: '19:00',
    arrivalTime: '23:00',
    duration: '28h 0m',
    from: 'Kolkata',
    to: 'Delhi',
    price: 3100,
    rating: 4.2,
    seats: createSeats(3100),
  },

  // Delhi to Kolkata
  {
    id: '34',
    name: 'Delhi-Howrah Janta',
    operator: 'Bengal Tours',
    departureTime: '16:00',
    arrivalTime: '19:00',
    duration: '27h 0m',
    from: 'Delhi',
    to: 'Kolkata',
    price: 3050,
    rating: 4.0,
    seats: createSeats(3050),
  },
  {
    id: '35',
    name: 'Capital-City of Joy',
    operator: 'National Travels',
    departureTime: '17:30',
    arrivalTime: '21:00',
    duration: '27h 30m',
    from: 'Delhi',
    to: 'Kolkata',
    price: 3250,
    rating: 4.2,
    seats: createSeats(3250),
  },
  {
    id: '36',
    name: 'Eastern Express',
    operator: 'Yatra Travels',
    departureTime: '18:00',
    arrivalTime: '22:00',
    duration: '28h 0m',
    from: 'Delhi',
    to: 'Kolkata',
    price: 3150,
    rating: 4.3,
    seats: createSeats(3150),
  },
];

export const trips: Trip[] = [
    {
        id: 'T1',
        busName: 'Blue Arrow Express',
        from: 'Mumbai',
        to: 'Pune',
        date: '2024-08-15',
        departureTime: '21:00',
        arrivalTime: '05:00',
        seatNumbers: ['12', '13'],
        fare: 1500,
        status: 'Upcoming'
    },
    {
        id: 'T2',
        busName: 'Orange Dart',
        from: 'Delhi',
        to: 'Jaipur',
        date: '2024-09-01',
        departureTime: '22:30',
        arrivalTime: '06:30',
        seatNumbers: ['7'],
        fare: 900,
        status: 'Upcoming'
    },
    {
        id: 'T3',
        busName: 'Comfort Cruiser',
        from: 'Bangalore',
        to: 'Chennai',
        date: '2024-07-20',
        departureTime: '20:00',
        arrivalTime: '04:30',
        seatNumbers: ['21', '22', '23'],
        fare: 2100,
        status: 'Completed'
    },
    {
        id: 'T4',
        busName: 'Blue Arrow Express',
        from: 'Pune',
        to: 'Mumbai',
        date: '2024-06-10',
        departureTime: '14:00',
        arrivalTime: '22:00',
        seatNumbers: ['A4'],
        fare: 750,
        status: 'Completed'
    },
    {
        id: 'T5',
        busName: 'Orange Dart',
        from: 'Mumbai',
        to: 'Goa',
        date: '2024-05-05',
        departureTime: '19:00',
        arrivalTime: '07:00',
        seatNumbers: ['3'],
        fare: 1200,
        status: 'Cancelled'
    },
]

export const getBusById = (id: string | undefined): Bus | undefined => {
    if (!id) return undefined;
    return buses.find(bus => bus.id === id);
}

export const getTripById = (id: string | undefined): Trip | undefined => {
    if (!id) return undefined;
    return trips.find(trip => trip.id === id);
}
